### ISSUE TITLE
Can't install via vscode in windows because raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1 not exist

### ISSUE THREAD

**Issue by linonetwo** [leanprover/elan#100]
```
Start-BitsTransfer -Source "https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1" -Destination "elan-init.ps1"
```

failed because https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1 is 404

**Comment by linonetwo** [comment]
Soved by download elan-x86_64-pc-windows-msvc.zip from github release

**Comment by Kha** [comment]
All I can say from here is that that URL definitely exists

**Comment by linonetwo** [comment]
Ok, it should be a severe network error on my side.
