### ISSUE TITLE
Deleting from `~/.elan/toolchains` but leaving matching `~/.elan/update-hashes` leaves elan in broken state.

### ISSUE THREAD

**Issue by semorrison** [leanprover/elan#107]
```
% elan toolchain install leanprover/lean4:v4.0.0
% rm -rf ~/.elan/toolchains/leanprover--lean4---v4.0.0
% lake +leanprover/lean4:v4.0.0 env                   
error: toolchain 'leanprover/lean4:v4.0.0' is not installed
% elan toolchain install leanprover/lean4:v4.0.0

  leanprover/lean4:v4.0.0 unchanged - (toolchain not installed)
% lake +leanprover/lean4:v4.0.0 env                     
error: toolchain 'leanprover/lean4:v4.0.0' is not installed
```

We had this happen on Hoskinson overnight!

It would be great if `elan` could detect this condition (toolchain apparently present in `update-hashes`, but missing in `toolchain`) and cope, either by cleaning up or explaining how to clean up.

To be fair, this is users abusing elan, but it's an easy failure mode for someone wanting to delete big files.

**Comment by Kha** [comment]
update-hashes will be gone with #106
