### ISSUE TITLE
[Feature request] support lean4

### ISSUE THREAD

**Issue by fghzxm** [leanprover/elan#30]
It looks like elan does not support updating Lean 4 toolchains:
```
$ elan -V
elan 1.0.0 (bc778de59 2021-04-17)
$ elan toolchain list
leanprover-lean4-nightly (default)
$ elan update
info: no updatable toolchains installed
info: checking for self-updates
```
It would be nice to have it work.

**Comment by Kha** [comment]
It looks like this is a pretty fundamental limitation with @khoek's changes for supporting arbitrary repositories - not sure if he's interested in taking another look :)

**Comment by Kha** [comment]
Ok, I gave a quick workaround a try after all. Please see the changelog of the linked commit and complain if I've broken anything.
