### ISSUE TITLE
Add Apple Silicon release

### ISSUE THREAD

**Issue by dwbcampbell** [leanprover/elan#34]
elan builds on apple silicon but running it gives:

Error(Download(HttpStatus(404)), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
error: could not download file from 'https://github.com/leanprover/elan/releases/download/v1.0.6/elan-aarch64-apple-darwin.tar.gz' to '/var/folders/56/x4pr_1lj4kb1rn96sj0h2yhr0000gn/T/elan-update.S0kxIPElRdh1/elan-aarch64-apple-darwin.tar.gz'

**Comment by Kha** [comment]
Yeah, there will not be any official Silicon releases of Lean until GitHub Actions supports it. Does the x86-64 release of elan work?

**Comment by dwbcampbell** [comment]
I can't install elan using the curl command.
But I can install lean 3 with brew.
I guess I will stick to lean 3.

**Comment by chadbrewbaker** [comment]
> Yeah, there will not be any official Silicon releases of Lean or elan until GitHub Actions supports it. Does the x86-64 release of elan work?

You can build under https://github.com/sickcodes/Docker-OSX. I would be fine with an option to self-compile for aarch64-darwin.
