### ISSUE TITLE
Not Functional on M1 Mac

### ISSUE THREAD

**Issue by donald-pinckney** [leanprover/elan#69]
Not sure if this is a duplicate of #34, but the README currently clearly says that (for Lean 4), I should be able to just use `elan`
to install an ARM-64 Lean 4:

> M1 Mac:
> Lean 4 has native macOS/aarch64 releases (nightly only so far) that you can install as above. 

Unfortunately, this doesn't actually work:

```bash
$ curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh
elan: unknown CPU type: arm64
```

**Comment by Kha** [comment]
Thanks for the report. I don't currently have access to an M1 machine. Could you try changing the script accordingly? Should be sufficient to change `aarch64)` to `arm64 | aarch64)`.

**Comment by donald-pinckney** [comment]
Ok, I did that, and the script now invokes the installer ok, but the installer can't find `darwin_aarch64` on nightly:

```bash
$ bash elan-init.sh --default-toolchain nightly -v -y
info: downloading installer
verbose: installing toolchain 'nightly'
verbose: toolchain directory: '/Users/donaldpinckney/.elan/toolchains/nightly'
info: syncing channel updates for 'nightly'
info: latest update on nightly, lean version nightly-2020-04-28
info: downloading component 'lean'
verbose: creating temp file: /Users/donaldpinckney/.elan/tmp/75uien5tfc47tr_z_file
verbose: downloading file from: 'https://github.com/leanprover-community/lean-nightly/releases/tag/nightly-2020-04-28'
verbose: downloading with curl
verbose: deleted temp file: /Users/donaldpinckney/.elan/tmp/75uien5tfc47tr_z_file
verbose: removing toolchain directory: '/Users/donaldpinckney/.elan/toolchains/nightly'
error: binary package was not provided for 'darwin_aarch64'
```

**Comment by donald-pinckney** [comment]
I'm not sure why `2020-04-28` is appearing in there, that seems really old...?

**Comment by donald-pinckney** [comment]
Ah, I see, I have to specify `leanprover/lean4:nightly` rather than `nightly`. Seems to install fine now! Shall I submit a PR for the script fix?

**Comment by Kha** [comment]
Yes, please do! Also feel free to update the readme, "that you can install as above" is not quite right as you pointed out (however, it should just work when installing from inside VS Code after your fix).

**Comment by donald-pinckney** [comment]
Ok, great, the PR is #70. Thanks again for the help!
