### ISSUE TITLE
elan-init fails with  --default-toolchain none

### ISSUE THREAD

**Issue by lovettchris** [leanprover/elan#73]
on [Linux CI build](https://github.com/leanprover/theorem_proving_in_lean4/runs/6267279445?check_suite_focus=true):
```
$ ./elan-init.sh -y
info: downloading installer
curl: (22) The requested URL returned error: 404
elan: command failed: curl -sSfL https://github.com/leanprover/elan/releases/download//elan-x86_64-unknown-linux-gnu.tar.gz -o /tmp/tmp.Kjsm5OvOQt/elan-init.tar.gz
```

**Comment by bryangingechen** [comment]
This seems to be affecting the CI in mathlib. Did something change in the last hour?

[Here's a log](https://github.com/leanprover-community/mathlib/runs/6265978321?check_suite_focus=true#step:3:15) from ~2 hours ago where the following command worked:
```
curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
```

[And here's a log](https://github.com/leanprover-community/mathlib/runs/6266696983?check_suite_focus=true#step:5:9) from about 15 minutes ago where the same command failed.

This was reported on Zulip [here](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/linter.20fails/near/280954501).

**Comment by lovettchris** [comment]
Weird that I can't repro this with a locally built version of elan...

**Comment by bentoner** [comment]
It seems like a change by github. Specifically [this line](https://github.com/leanprover/elan/blob/7d84490fdba737874e9cad1911182bbd1716e648/elan-init.sh#L101) no longer works, at least locally for me. https://github.com/leanprover/elan/releases/latest now returns a 302 to  https://github.com/leanprover/elan/releases/tag/v1.4.1 with no content.

@lovettchris can you share what `curl -sSf https://github.com/leanprover/elan/releases/latest` returns locally for you?

**Comment by lovettchris** [comment]
I think I found a fix.

**Comment by bentoner** [comment]
Works for me (noting I don't understand the curl magic).
