### ISSUE TITLE
Reuse already downloaded toolchain

### ISSUE THREAD

**Issue by iacore** [leanprover/elan#77]
Currently, lake/leanpkg doesn't reuse toolchain versions.

## How to reproduce

1. `elan default leanprover/lean4:nightly`
2. `lake init foo`
  which produce `lean-toolchain` with `4.0.0-nightly-2022-07-19` (which is the same version already installed)
3. `lake build`
  It's downloading the same nightly version again

**Comment by Kha** [comment]
Fixed by #106
